language: ruby
rvm:
  - 2.1.2
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database iota-project_test' -U postgres
deploy:
  provider: heroku
  api_key: 5f124ede-0ad0-4b74-958e-9057685aa737
  app: iota-project